function strengthBest(t){return ({Argentina:96,France:93,Spain:92,England:90,Belgium:82,Morocco:72,Norway:71,Colombia:80,Switzerland:78})[t]||60}
function probBest(a,b){if(a.team==='TBD')return 0;if(b.team==='TBD')return 1;var p=strengthBest(a.team)/(strengthBest(a.team)+strengthBest(b.team));return Math.max(.12,Math.min(.88,p))}
function rowBest(t,o){return{team:t,owner:o}}
function baseBest(){return [[rowBest('France','Knox'),rowBest('Morocco','Nolan')],[rowBest('Spain','Whelan'),rowBest('Belgium','Dolan')],[rowBest('Norway','Knox'),rowBest('England','McCartney')],[rowBest('Argentina','J. Schwartz'),rowBest('TBD','')]]}
function simBest(){var b=baseBest();var q=b.map(function(x){return{paths:[{team:x[0].team,owner:x[0].owner,p:probBest(x[0],x[1])},{team:x[1].team,owner:x[1].owner,p:1-probBest(x[0],x[1])}].filter(function(y){return y.team!=='TBD'&&y.p>0})}});var s1={paths:[]};q[0].paths.forEach(function(a){q[1].paths.forEach(function(c){var pa=probBest(a,c);s1.paths.push({team:a.team,owner:a.owner,p:a.p*c.p*pa});s1.paths.push({team:c.team,owner:c.owner,p:a.p*c.p*(1-pa)})})});var s2={paths:[]};q[2].paths.forEach(function(a){q[3].paths.forEach(function(c){var pa=probBest(a,c);s2.paths.push({team:a.team,owner:a.owner,p:a.p*c.p*pa});s2.paths.push({team:c.team,owner:c.owner,p:a.p*c.p*(1-pa)})})});var wins={};s1.paths.forEach(function(a){s2.paths.forEach(function(c){var pa=probBest(a,c);wins[a.owner]=(wins[a.owner]||0)+a.p*c.p*pa;wins[c.owner]=(wins[c.owner]||0)+a.p*c.p*(1-pa)})});var owned={Knox:['France','Norway'],Nolan:['Morocco'],Whelan:['Spain'],Dolan:['Belgium'],McCartney:['England'],'J. Schwartz':['Argentina']};return Object.keys(wins).map(function(o){return{o:o,p:wins[o]*100,teams:owned[o]||[]}}).sort(function(a,b){return b.p-a.p})}
simulate=function(){return simBest()}
alive=function(){return [['France','Knox'],['Morocco','Nolan'],['Spain','Whelan'],['Belgium','Dolan'],['Norway','Knox'],['England','McCartney'],['Argentina','J. Schwartz']]}
ownerCards=function(){var m={};alive().forEach(function(x){m[x[1]]=m[x[1]]||{live:[],out:[]};m[x[1]].live.push(x[0])});return m}
render()
