window.HRD=window.HRD||{};
(function(){
 const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
 const eventComplete=()=>Boolean(HRD.config?.eventComplete)||/complete|completed|champion|final score/i.test(String(HRD.state.eventStatus||''));
 const liveSorted=()=>[...HRD.players].sort((a,b)=>eventComplete()?(b.hr-a.hr):b.hr-a.hr||(Number(b.stats?.maxDistance)||0)-(Number(a.stats?.maxDistance)||0)||a.name.localeCompare(b.name));
 const fmt=(value,digits=0)=>value==null?'—':Number(value).toFixed(digits);
 const projectionFor=p=>(HRD.projections||[]).find(r=>r.name===p?.name);
 const slot=(p,label,value)=>`<div class="slot"><span><span class="seed">${label}</span> ${p?.name||'TBD'}<br><span class="owner">${p?.owner||''}</span></span><strong>${value??'—'}</strong></div>`;
 const statLine=(label,value)=>`<div class="stat-line"><span>${label}</span><strong>${value}</strong></div>`;
 function playerStats(p){const s=p.stats||HRD.emptyStats(),r=p.rounds||{};if(eventComplete())return `<div class="stat-grid">${statLine('Round 1',r.round1??'—')}${statLine('Semifinal',r.semifinal??'—')}${statLine('Final',r.final??'—')}${statLine('Event total',p.hr)}${statLine('Max distance',s.maxDistance==null?'—':`${fmt(s.maxDistance)} ft`)}${statLine('Tracked Statcast',s.trackedHomers==null?'—':s.trackedHomers)}</div>`;return `<div class="stat-grid">${statLine('Max distance',s.maxDistance==null?'—':`${fmt(s.maxDistance)} ft`)}${statLine('Avg distance',s.avgDistance==null?'—':`${fmt(s.avgDistance)} ft`)}${statLine('Max exit velo',s.maxExitVelocity==null?'—':`${fmt(s.maxExitVelocity,1)} mph`)}${statLine('Avg exit velo',s.avgExitVelocity==null?'—':`${fmt(s.avgExitVelocity,1)} mph`)}${statLine(`Bonus HRs (${HRD.config.bonusDistance}+ ft)`,s.bonusHomers==null?'—':s.bonusHomers)}${statLine('Tracked HRs',s.trackedHomers==null?'—':s.trackedHomers)}${statLine('Last distance',s.lastDistance==null?'—':`${fmt(s.lastDistance)} ft`)}${statLine('Last exit velo',s.lastExitVelocity==null?'—':`${fmt(s.lastExitVelocity,1)} mph`)}</div>`}
 function moveOddsToTop(){const simulation=document.getElementById('simulation'),hero=document.querySelector('.hero'),card=simulation?.closest('.card');if(card&&hero&&hero.nextElementSibling!==card)hero.insertAdjacentElement('afterend',card)}
 const scoringStarted=()=>HRD.players.some(p=>(Number(p.hr)||0)>0);
 function projectedOrder(fallback){const byName=new Map(HRD.players.map(p=>[p.name,p]));const projected=(HRD.projections||[]).map(r=>byName.get(r.name)).filter(Boolean);return projected.length===HRD.players.length?projected:fallback}
 function renderSticky(leader,isProjected){const root=document.getElementById('stickyLive');if(!root)return;const completed=eventComplete(),detail=completed?'2026 Home Run Derby complete':[HRD.state.currentHitter&&`Hitting: ${HRD.state.currentHitter}`,HRD.state.timeRemaining&&`Time: ${HRD.state.timeRemaining}`,HRD.state.outsRemaining!=null&&`Outs: ${HRD.state.outsRemaining}`].filter(Boolean).join(' · ')||HRD.state.eventStatus;const projection=projectionFor(leader);const leaderText=!leader?'Waiting':isProjected?`${leader.owner} · ${(projection?.win*100||0).toFixed(1)}% win`:`${leader.owner} · ${leader.hr} total HR`;root.innerHTML=`<span class="live-dot idle"></span><div><strong>${completed?'FINAL':HRD.state.isLive?'LIVE':'MLB'}</strong><small>${detail}</small></div><div class="sticky-leader"><small>${completed?'Champion':isProjected?'Projected leader':'Current leader'}</small><strong>${leaderText}</strong></div>`}
 function renderHighlights(){const root=document.getElementById('highlights');if(!root)return;const long=HRD.state.biggestHomer,hard=HRD.state.hardestHit;root.innerHTML=`<div class="highlight"><span>🚀 Biggest homer</span><strong>${long?`${fmt(long.value)} ft`:'—'}</strong><small>${long?`${long.owner} · ${long.name}`:'No official Statcast value'}</small></div><div class="highlight"><span>🔥 Hardest hit</span><strong>${hard?`${fmt(hard.value,1)} mph`:'—'}</strong><small>${hard?`${hard.owner} · ${hard.name}`:'Not published'}</small></div><div class="highlight"><span>${eventComplete()?'🏆 Champion':'⏱ Current hitter'}</span><strong>${eventComplete()?'Jordan Walker':HRD.state.currentHitter||'—'}</strong><small>${eventComplete()?'Roynan · 31 total HR':'Shown when MLB publishes it'}</small></div>`}
 HRD.render=function(){
  const live=liveSorted(),changed=new Set(HRD.state.changedPlayers||[]),completed=eventComplete();
  if(completed){HRD.projections=[];document.getElementById('simulation').innerHTML='<div class="last-play">🏆 <strong>Jordan Walker — 2026 Home Run Derby champion</strong><br>Defeated Kyle Schwarber 12–11 in the final.</div>'}else if(HRD.renderSimulation)HRD.renderSimulation();
  const isProjected=!completed&&!scoringStarted(),display=isProjected?projectedOrder(live):live;
  document.getElementById('leaderboard').innerHTML=`<div class="sim-note">${completed?'Final ranking by total home runs across all rounds.':isProjected?'Ranked by Monte Carlo win probability before scoring.':'Ranked by live MLB home-run totals; distance breaks ties.'}</div>`+display.map((p,i)=>`<div class="player-card ${completed&&i===0?'leader':''} ${changed.has(p.name)?'just-scored':''}"><div class="player"><div class="rank">${i+1}</div><div><div class="name">${p.name}</div><div class="owner">Owner: ${p.owner}${completed&&i===0?' · Champion':''}</div></div><div class="score">${isProjected?`${((projectionFor(p)?.win||0)*100).toFixed(1)}%`:p.hr}<small>${isProjected?'WIN ODDS':completed?'TOTAL HR':'HOME RUNS'}</small></div></div>${playerStats(p)}</div>`).join('');
  if(completed){const byName=Object.fromEntries(HRD.players.map(p=>[p.name,p]));document.getElementById('bracket').innerHTML=`<div class="sim-note">Final 2026 Derby bracket.</div><div class="match"><div class="match-title">Semifinal 1</div>${slot(byName['Kyle Schwarber'],'#4',9)}${slot(byName['Willson Contreras'],'#1',8)}</div><div class="match"><div class="match-title">Semifinal 2</div>${slot(byName['Jordan Walker'],'#2',6)}${slot(byName['Junior Caminero'],'#3',5)}</div><div class="match"><div class="match-title">Final</div>${slot(byName['Jordan Walker'],'Champion',12)}${slot(byName['Kyle Schwarber'],'Runner-up',11)}<div class="last-play">🏆 Jordan Walker won 12–11.</div></div>`}else{const adv=display.slice(0,4),m1=[adv[0],adv[3]],m2=[adv[1],adv[2]];if(isProjected){const finalists=[...adv].sort((a,b)=>(projectionFor(b)?.final||0)-(projectionFor(a)?.final||0)).slice(0,2),champ=[...adv].sort((a,b)=>(projectionFor(b)?.win||0)-(projectionFor(a)?.win||0))[0];document.getElementById('bracket').innerHTML=`<div class="sim-note">Projected from Monte Carlo simulations.</div><div class="match"><div class="match-title">Projected Semifinal 1</div>${slot(m1[0],'#1',`${((projectionFor(m1[0])?.semi||0)*100).toFixed(1)}%`)}${slot(m1[1],'#4',`${((projectionFor(m1[1])?.semi||0)*100).toFixed(1)}%`)}</div><div class="match"><div class="match-title">Projected Semifinal 2</div>${slot(m2[0],'#2',`${((projectionFor(m2[0])?.semi||0)*100).toFixed(1)}%`)}${slot(m2[1],'#3',`${((projectionFor(m2[1])?.semi||0)*100).toFixed(1)}%`)}</div><div class="last-play">Projected champion: <strong>${champ?.name||'TBD'}</strong></div>`}else{document.getElementById('bracket').innerHTML=`<div class="sim-note">Seeds follow live MLB totals.</div><div class="match"><div class="match-title">Semifinal 1</div>${slot(m1[0],'#1',m1[0]?.hr)}${slot(m1[1],'#4',m1[1]?.hr)}</div><div class="match"><div class="match-title">Semifinal 2</div>${slot(m2[0],'#2',m2[0]?.hr)}${slot(m2[1],'#3',m2[1]?.hr)}</div>`}}
  const total=HRD.players.reduce((n,p)=>n+p.hr,0);document.getElementById('status').innerHTML=`<div class="player"><div class="rank">${total}</div><div><div class="name">${HRD.state.eventStatus}</div><div class="owner">Source: ${HRD.state.source}</div></div><div class="score">${display[0]?.hr||0}<small>${completed?'CHAMPION TOTAL':'CURRENT LEADER'}</small></div></div>${HRD.state.lastPlay?`<div class="last-play">${esc(HRD.state.lastPlay)}</div>`:''}`;
  renderSticky(display[0],isProjected);renderHighlights();
 };
 window.launchBall=function(){const ball=document.createElement('div');ball.className='flying-ball';ball.textContent='⚾';document.body.appendChild(ball);setTimeout(()=>ball.remove(),1400)};
 window.shareApp=async function(){try{await navigator.share({title:'HR Dinger Pool 2026',url:location.href})}catch(e){await navigator.clipboard.writeText(location.href);alert('Link copied')}};
 window.refreshFromMlb=()=>HRD.refreshFromMlb();
 moveOddsToTop();HRD.render();HRD.startAutoRefresh();
})();